### ISSUE TITLE
CI/CD Tutorial:  Push to Docker fails if GitHub and Docker usernames are different

### ISSUE THREAD

**Issue by dodsonmg** [olliefr/docker-gs-ping#3]
https://github.com/olliefr/docker-gs-ping/blob/003af377116d4ba8f577ccefd2f21395b9bc09bf/.github/workflows/release.yml#L37

I think the above line requires modification if the user's GitHub and Docker Hub usernames don't match.  It might be worth noting in the CI/CD portion of the tutorial.

I'd be happy to submit a PR, but I think my own solution is a bit of a hack and probably not what you want either here or in the tutorial.  I'm sure there's a smarter way to use `secrets.DOCKER_HUB_USERNAME`, but I can't figure it out.

I'm also not sure whether the PR should start with the code repo or the tutorial repo, so I figured I'd start with a discussion here first.

More details below.

---

First, this is such a useful tutorial.  The CI/CD portion particularly has been tremendously helpful.  I'm new to Docker (hence going through tutorials) and had no real intuition for how people were using it for CD in particular.  The tutorial's style and simple examples have brought me a long way.  Thank you.

Now to the issue:

The release workflow was failing during the `Build and push Docker image` step with the following:

```
#12 pushing dodsonmg/docker-gs-ping:latest with docker
#12 pushing layer bb0e01146d01
...
#12 pushing layer 72e830a4dff5 0.3s done
#12 ERROR: denied: requested access to the resource is denied
------
 > pushing dodsonmg/docker-gs-ping:latest with docker:
------
error: denied: requested access to the resource is denied
Error: buildx failed with: error: denied: requested access to the resource is denied
```

For no useful reason, I had different usernames for GitHub and Docker Hub.  `${{ github.repository }}` resolves to `dodsonmg/docker-gs-ping` (as you can see above...); however, since `dodsonmg` wasn't my Docker Hub username, the push was failing, despite the fact that the `Login to Docker Hub` step was passing.

I modified the line to:
`tags: md403/docker-gs-ping:latest` (`md403` being my Docker Hub username) and it worked fine.

Thankfully, my GitHub username is also available on Docker Hub, so I changed it and the repo code works as expected without modifications.

**Comment by dodsonmg** [comment]
I started poking at the issues and PRs for the other tutorials and found a few that were related, but not exactly the same.  Going through the Java tutorial, however, I see that they use:

```
tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simplewhale:latest
```
instead of
```
tags: ${{ github.repository }}:latest
```

So they have to hardcode the docker repo name, but not the docker username.

Happy to PR this, if you're interested.  Preference on order (code repo then tutorial repo)?

**Comment by olliefr** [comment]
Hey, @dodsonmg, thank you for reporting this!

Well spotted, I've made an undocumented assumption.  My GitHub and Docker Hub usernames are the same.

Good examples for tutorials are _very_ hard to set up. There are multiple dimensions which must be kept in mind, such as clarity of exposition, technical correctness, conciseness, and so on.

But in this case an edit is, indeed, warranted. I've done a bit of research (please see my [olliefr/docker-hub-github-workflow-test repo](https://github.com/olliefr/docker-hub-github-workflow-test) for this, if interested) and found a way to extract the name of the repository from the event data:

```yaml
tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest
```

https://github.com/olliefr/docker-hub-github-workflow-test/blob/4154d165635493899a9c021516e433f429f8255d/.github/workflows/release.yml#L26 

I've tested this change by creating a new Docker Hub user `sadtemp` which, obviously, is different from my GitHub username @olliefr. I was able to successfully build and publish the image to the Docker Hub.

* With respect to PRs, please feel free to submit the PR for this repo, implementing the change as described above.
* If you do, please also submit a PR to the Docker Documentation so that this repo and the example in the documentation are in sync. Please note the documentation PR id in the comment to your PR to this repo.
* If you feel particularly adventurous, the trick I've mentioned in this comment can also be applied to the Dockerfile for Java example in Docker documentation (the one that you referenced).

Let's get this fixed! :shipit: 😄

**Comment by dodsonmg** [comment]
I've submitted the PR.

Relatedly, is the `tags` line in `ci.yml` meant to have the same intent?

https://github.com/olliefr/docker-gs-ping/blob/003af377116d4ba8f577ccefd2f21395b9bc09bf/.github/workflows/ci.yml#L44

That is, is that second tag meant to include the Docker Hub or the GitHub username?  As written, it resolves to include the GitHub username.

Fixing this one would be harder because `ci.yml` doesn't already include Docker Hub secrets.

Admittedly, I don't actually understand how these tags are used in the CI workflow.  I think they're related to caching, so maybe a tag with the GitHub username is both correct and necessary.

Thoughts?

**Comment by olliefr** [comment]
@dodsonmg, `ci.yml` is a different story. That workflow does not push to Docker Hub, I only use Docker GitHub Action to build the programme for testing, so it does not really matter what we tag it as. 

In a "real" scenario, you'd most probably want to have a single "build" step, with the artefact produced by that step feeding both into the CI pipeline, and then, if successful, into the Docker Hub. But I feel that for the tutorial purposes, that's an overkill. As I said before, there is a fine line to walk when writing tutorials.

The `release` workflow was totally worth fixing, though. Thank you!
