### ISSUE TITLE
Adding Testconstainers for Go

### ISSUE THREAD

**Issue by mdelapenya** [olliefr/docker-gs-ping#6]
Hi :wave: from [Testcontainers for Go](https://github.com/testcontainers/testcontainers-go) community!

We'd like to contribute a PR including copies of the existing tests, using `Testcontainers for Go`.

Do you think it could be something to discuss? Thanks in advance!

**Comment by olliefr** [comment]
Thank you for raising this issue, @mdelapenya. Please accept my apologies for having missed this at first.

I'm game for more examples! If you can figure out how to re-structure the repo so that both examples can coexist without adversely affecting the brevity and clarity of the code, let's do it. Please feel free to submit the PR.

**Comment by mdelapenya** [comment]
> I'm game for more examples! If you can figure out how to re-structure the repo so that both examples can coexist without adversely affecting the brevity and clarity of the code, let's do it. Please feel free to submit the PR.

PR is there :) I'd appreciate your feedback in the PR 🙏

**Comment by olliefr** [comment]
Replied in #7
